# To get your DISCORD_WEBHOOK_URL - right click your server --> server settings --> integrations

name: "Notification regarding New Pull Request via Discord"

on:
  pull_request_target: 
    types: [opened] 
  #  issue_comment:
  #    types: [created] # temp for test reasons

jobs:
  notifyViaDiscord:
    runs-on: ubuntu-latest

    steps:
      - uses: denolib/setup-deno@v2
        with:
         deno-version: v1.x
      - run: deno run --allow-net https://deno.land/x/cicd/notify-via-discord.ts ${{ secrets.DISCORD_WEBHOOK_URL }} ${{ github.repository }} "Pull Request Created - ${{ github.event.pull_request.html_url }}"

# https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
