name: Ship

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
         deno-version: v1.4.6
      - name: Publish module
        run: |
          deno run -A --unstable https://x.nest.land/eggs@0.3.0/eggs.ts link ${{ secrets.NESTAPIKEY }}
          deno run -A --unstable https://x.nest.land/eggs@0.3.0/eggs.ts publish --version ${{ github.event.inputs.version }}
