# name: "publish current release to nest.land 2"

# on: # commented as currently using publish-to-nest.land.yml
#   release:
#     types:
#       - created

# jobs:
#   publishToNestDotLand:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Setup repo
#         uses: actions/checkout@v2

#       - name: "setup" # check: https://github.com/actions/virtual-environments/issues/1777
#         uses: denolib/setup-deno@v2 
#         with:
#          deno-version: v1.4.6
#       - run: deno install -Af --unstable https://x.nest.land/eggs@0.3.1/eggs.ts
          
#       - name: Set env
#         run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

#       - name: "Publish to nest.land" # check: https://docs.nest.land/eggs/publishing-a-module.html
#         run: |
#           export PATH="/home/runner/.deno/bin:$PATH"
#           eggs link ${{ secrets.NESTAPIKEY }}
#           eggs publish --version ${{ env.RELEASE_VERSION }} --no-check -Y
